# Generated by Django 5.1.1 on 2024-09-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctorings', '0004_subject_question_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('face_count', models.IntegerField()),
                ('detected_objects', models.TextField()),
                ('head_pose', models.CharField(max_length=100)),
                ('gaze_direction', models.CharField(max_length=100)),
                ('cheating_count', models.IntegerField()),
            ],
        ),
    ]
